#!/bin/sh

path1="/home/prezdev/git-projects/"
projects_path1=$(find "$path1" -maxdepth 1 -mindepth 1 -type d -printf '%p\n')
projects=$(printf "%s\n%s\n%s\n" "$projects_path1")

echo "$projects" | rofi -dmenu -p "Open project" -lines 10 -width 1000 | xargs -I {} code {}
